apiVersion: apps/v1
kind: Deployment
metadata:
  name: jci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jci
  template:
    metadata:
      labels:
        app: jci
    spec:
      containers:
      - name: jci
        image: jci:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000