apiVersion: apps/v1
kind: Deployment
metadata:
  name: jack-change-it-1.0.0
  labels:
    app: jack-change-it-1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jack-change-it-1.0.0
  template:
    metadata:
      labels:
        app: jack-change-it-1.0.0
    spec:
      containers:
      - name: jack-change-it-1.0.0
        image: jack-change-it-1.0.0
        ports:
        - containerPort: 8000
